id: P007058
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25343
  title: ཀུན་མཁྱེན་ཕར་ཕྱིན་མཐའ་དཔྱོད།
  author: ''
  volumes:
    c768f76cda4a47b79ae20b679dc23603:
      image_group_id: I1KG25345
      title: ''
      volume_number: 1
      total_pages: 632
    04b40b4623894d2eac91ef9b73d85f25:
      image_group_id: I1KG25346
      title: ''
      volume_number: 2
      total_pages: 590
ebook_metadata:
  title: ཀུན་མཁྱེན་ཕར་ཕྱིན་མཐའ་དཔྱོད།
  author: ''
  sku: P007058
  cover: cover.jpg
  layers:
  - pagination
