id: P007058
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 12:38:58.706325
source_metadata:
  id: bdr:W1KG25343
  title: ཀུན་མཁྱེན་ཕར་ཕྱིན་མཐའ་དཔྱོད།
  author: ''
  volumes:
    4545a28f87fd454bb9c0256a1387d271:
      image_group_id: I1KG25345
      title: Volume 1 of kun mkhyen phar phyin mtha' dpyod/
      volume_number: 1
      total_pages: 632
      base_file: v001.txt
    a56846d27a0e49848711fb0f674b113d:
      image_group_id: I1KG25346
      title: Volume 2 of kun mkhyen phar phyin mtha' dpyod/
      volume_number: 2
      total_pages: 590
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
